/**
 * Builds the game's Kenney sprites (kenney.nl, CC0) from the official
 * downloads: every pack in scripts/kenney/sprites.json is fetched once into
 * .cache/kenney/, and each sprite named there is written to
 * public/kenney/<name>.svg - a file from the pack as it is, or one sprite
 * cut from a sheet (sliceSheet.mjs). Also writes the licence note next to
 * them, and src/game/scenes/spriteNames.ts so the code can only ask for
 * sprites that exist.
 *
 *   npm run kenney
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { sliceSheet } from "./sliceSheet.mjs";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")), "../..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "scripts/kenney/sprites.json"), "utf8"));
const cache = path.join(root, ".cache/kenney");
const out = path.join(root, "public/kenney");
fs.mkdirSync(cache, { recursive: true });
fs.mkdirSync(out, { recursive: true });

/** A pack's files, downloaded and unpacked once. */
async function unpacked(packId) {
  const pack = manifest.packs[packId];
  const dir = path.join(cache, packId);
  if (fs.existsSync(path.join(dir, ".done"))) return dir;
  const zip = path.join(cache, `${packId}.zip`);
  if (!fs.existsSync(zip)) {
    console.log(`downloading ${pack.name} …`);
    const res = await fetch(pack.zip);
    if (!res.ok) throw new Error(`${pack.zip}: HTTP ${res.status}`);
    fs.writeFileSync(zip, Buffer.from(await res.arrayBuffer()));
  }
  fs.mkdirSync(dir, { recursive: true });
  try {
    execFileSync("unzip", ["-oq", zip, "-d", dir], { stdio: "ignore" });
  } catch {
    execFileSync("tar", ["-xf", zip, "-C", dir]); // Windows' tar reads zips too
  }
  fs.writeFileSync(path.join(dir, ".done"), "");
  return dir;
}

const sheets = new Map();
async function sheetSprites(packId, file) {
  const key = `${packId}:${file}`;
  if (!sheets.has(key)) sheets.set(key, sliceSheet(fs.readFileSync(path.join(await unpacked(packId), file), "utf8")));
  return sheets.get(key);
}

const names = Object.keys(manifest.sprites).sort();
for (const name of names) {
  const s = manifest.sprites[name];
  let svg;
  if (s.file) svg = fs.readFileSync(path.join(await unpacked(s.pack), s.file), "utf8");
  else {
    const sprites = await sheetSprites(s.pack, s.sheet);
    if (!sprites[s.index]) throw new Error(`${name}: ${s.sheet} has no sprite ${s.index}`);
    svg = sprites[s.index].svg;
  }
  fs.writeFileSync(path.join(out, `${name}.svg`), svg.trim() + "\n");
}

// The licence, and which packs the sprites come from.
const packsUsed = [...new Set(names.map((n) => manifest.sprites[n].pack))].map((id) => manifest.packs[id]);
fs.writeFileSync(
  path.join(out, "LICENSE.txt"),
  `The sprites in this folder are by Kenney (www.kenney.nl), from:\n${packsUsed.map((p) => `  - ${p.name}: ${p.page}`).join("\n")}\n\nLicense: Creative Commons Zero (CC0) - http://creativecommons.org/publicdomain/zero/1.0/\nThey may be used in personal and commercial projects. Credit is not required, but given gladly.\n\nRebuilt from the official downloads with: npm run kenney (scripts/kenney/).\n`
);
fs.writeFileSync(
  path.join(root, "src/game/scenes/spriteNames.ts"),
  `// Generated by scripts/kenney/build.mjs from scripts/kenney/sprites.json - do not edit.\n/** The Kenney sprites in public/kenney/ (CC0, kenney.nl). */\nexport type SpriteName =\n${names.map((n) => `  | "${n}"`).join("\n")};\n`
);
console.log(`${names.length} sprites written to public/kenney/`);
