/**
 * columnMul: written column multiplication (uppställning), single-digit
 * multiplier only (stages 2.1.1-2.1.3: e.g. 23 · 3, 47 · 6, 347 · 6).
 *
 * Scope note: a multi-digit multiplier needs one partial-product row per
 * multiplier digit plus a final column addition of those rows (CellType
 * already reserves "partialProduct"/"placeholderZero" and Cell.row for this,
 * see build brief "2.1 Skriftlig multiplikation" stages 4-6) - that is a
 * real UI rewrite (ColumnBoard/board.ts are single-row today) left for a
 * follow-up. A single-digit multiplier needs only one row, so it reuses the
 * exact same single-row cell/board shape as columnAdd.
 *
 * Convention: a multiplication carry generated at column `i` (from
 * top[i]*multiplier+carryIn) is displayed above column `i+1`, same as
 * columnAdd's addition carry.
 */
import { digitAt, digitsOf } from "../digits";
import type { BuildOptions, Cell, CellGraph, CellValue, CheckReport, WrittenMap } from "../types";

export interface ColumnMulParams {
  top: number;
  bottom: number; // single digit, 1-9 (see assertSingleDigitMultiplier)
}

interface MulColumnPlan {
  col: number;
  topDigit: number;
  carryOut: number;
  resultDigit: number;
}

function assertSingleDigitMultiplier(bottom: number): void {
  if (!Number.isInteger(bottom) || bottom < 1 || bottom > 9) {
    throw new Error(`columnMul (v1): multiplier must be a single digit 1-9, got ${bottom}`);
  }
}

function computeMultiplicationPlan(top: number, bottom: number): { columns: MulColumnPlan[]; overflowDigit: number | null } {
  assertSingleDigitMultiplier(bottom);
  const n = digitsOf(top).length;
  const columns: MulColumnPlan[] = [];
  let carryIn = 0;
  for (let col = 0; col < n; col++) {
    const topDigit = digitAt(top, col);
    const product = topDigit * bottom + carryIn;
    const resultDigit = product % 10;
    const carryOut = Math.floor(product / 10);
    columns.push({ col, topDigit, carryOut, resultDigit });
    carryIn = carryOut;
  }
  return { columns, overflowDigit: carryIn > 0 ? carryIn : null };
}

function resultId(col: number): string {
  return `mul-r${col}`;
}
function carryId(col: number): string {
  // carryId(col) is the minnessiffra generated BY column `col`, shown above column col+1.
  return `mul-c${col}`;
}

export function buildGraph(params: ColumnMulParams, _options?: BuildOptions): CellGraph {
  const { top, bottom } = params;
  const { columns, overflowDigit } = computeMultiplicationPlan(top, bottom);
  const cells: Cell[] = [];
  let previousColumnCellIds: string[] = [];

  for (const c of columns) {
    const columnCellIds: string[] = [];

    cells.push({
      id: resultId(c.col),
      type: "result",
      col: c.col,
      row: 0,
      expected: c.resultDigit,
      required: true,
      dependsOn: [...previousColumnCellIds],
    });
    columnCellIds.push(resultId(c.col));

    // A carry cell exists for every column except the last (its carry, if any,
    // becomes the overflow leading digit instead). A minnessiffra of 0 is never
    // written, so it is present but not required.
    if (c.col < columns.length - 1) {
      cells.push({
        id: carryId(c.col),
        type: "carry",
        col: c.col + 1,
        row: 0,
        expected: c.carryOut,
        required: c.carryOut > 0,
        dependsOn: [...previousColumnCellIds],
      });
      columnCellIds.push(carryId(c.col));
    }

    previousColumnCellIds = columnCellIds;
  }

  if (overflowDigit !== null) {
    cells.push({
      id: resultId(columns.length),
      type: "result",
      col: columns.length,
      row: 0,
      expected: overflowDigit,
      required: true,
      dependsOn: [...previousColumnCellIds],
    });
  }

  return { cells };
}

/**
 * Checks every cell against the true value, then (for result cells, whose
 * expected value depends on an earlier written carry) against the value that
 * follows from the child's own earlier entries - a result wrong only because
 * an earlier multiplication carry was mis-copied is a följdfel, not a fresh
 * error. Mirrors columnAdd's checkAll exactly, with product instead of sum.
 */
export function checkAll(params: ColumnMulParams, written: WrittenMap): CheckReport {
  const { top, bottom } = params;
  const { columns, overflowDigit } = computeMultiplicationPlan(top, bottom);
  const results: CheckReport["results"] = [];
  let errorCount = 0;
  let followOnErrorCount = 0;

  const carryWritten = (col: number): number | undefined => {
    const v = written[carryId(col)];
    return typeof v === "number" ? v : undefined;
  };

  for (const c of columns) {
    const carryIn = c.col === 0 ? 0 : carryWritten(c.col - 1);
    const trueProduct = c.topDigit * bottom + (c.col === 0 ? 0 : columns[c.col - 1].carryOut);
    const trueExpected = trueProduct % 10;
    const followOnExpected = carryIn === undefined ? trueExpected : (c.topDigit * bottom + carryIn) % 10;

    results.push(
      classify(resultId(c.col), written[resultId(c.col)], trueExpected, followOnExpected, true, (s) => {
        if (s === "wrong") errorCount++;
        if (s === "followOnError") followOnErrorCount++;
      })
    );

    if (c.col < columns.length - 1) {
      // Carry cells never depend on another written value - always structural.
      results.push(
        classify(carryId(c.col), written[carryId(c.col)], c.carryOut, c.carryOut, c.carryOut > 0, (s) => {
          if (s === "wrong") errorCount++;
        })
      );
    }
  }

  if (overflowDigit !== null) {
    results.push(
      classify(resultId(columns.length), written[resultId(columns.length)], overflowDigit, overflowDigit, true, (s) => {
        if (s === "wrong") errorCount++;
      })
    );
  }

  return {
    results,
    errorCount,
    followOnErrorCount,
    allCorrect: results.every((r) => r.status === "correct" || r.status === "notRequired"),
  };
}

function classify(
  cellId: string,
  writtenValue: CellValue | undefined,
  trueExpected: CellValue,
  followOnExpected: CellValue,
  required: boolean,
  tally: (status: "correct" | "wrong" | "followOnError" | "unattempted" | "notRequired") => void
): CheckReport["results"][number] {
  if (!required) {
    tally("notRequired");
    return { cellId, status: "notRequired" };
  }
  if (writtenValue === undefined) {
    tally("unattempted");
    return { cellId, status: "unattempted" };
  }
  if (writtenValue === trueExpected) {
    tally("correct");
    return { cellId, status: "correct" };
  }
  if (writtenValue === followOnExpected) {
    tally("followOnError");
    return { cellId, status: "followOnError" };
  }
  tally("wrong");
  return { cellId, status: "wrong" };
}
