/**
 * columnAdd: written column addition with minnessiffra (uppställning med minnessiffra).
 *
 * Convention: a carry cell generated at column `i` (from top[i]+bottom[i]+carryIn)
 * is displayed above column `i+1`, per Swedish textbook layout. A carry out of the
 * last column becomes a new leading result digit (no minnessiffra cell for it).
 */
import { digitAt, digitsOf } from "../digits";
import type {
  BuildOptions,
  Cell,
  CellGraph,
  CellValue,
  CheckReport,
  WrittenMap,
} from "../types";

export interface ColumnAddParams {
  top: number;
  bottom: number;
}

interface AddColumnPlan {
  col: number;
  topDigit: number;
  bottomDigit: number;
  carryOut: number; // 0 or 1
  resultDigit: number; // ones digit of the column sum
}

function computeAdditionPlan(top: number, bottom: number): { columns: AddColumnPlan[]; overflowDigit: number | null } {
  const n = Math.max(digitsOf(top).length, digitsOf(bottom).length);
  const columns: AddColumnPlan[] = [];
  let carryIn = 0;
  for (let col = 0; col < n; col++) {
    const topDigit = digitAt(top, col);
    const bottomDigit = digitAt(bottom, col);
    const sum = topDigit + bottomDigit + carryIn;
    const resultDigit = sum % 10;
    const carryOut = Math.floor(sum / 10);
    columns.push({ col, topDigit, bottomDigit, carryOut, resultDigit });
    carryIn = carryOut;
  }
  return { columns, overflowDigit: carryIn > 0 ? carryIn : null };
}

function resultId(col: number): string {
  return `add-r${col}`;
}
function carryId(col: number): string {
  // carryId(col) is the minnessiffra generated BY column `col`, shown above column col+1.
  return `add-c${col}`;
}

export function buildGraph(params: ColumnAddParams, _options?: BuildOptions): CellGraph {
  const { top, bottom } = params;
  const { columns, overflowDigit } = computeAdditionPlan(top, bottom);
  const cells: Cell[] = [];
  let previousColumnCellIds: string[] = [];

  for (const c of columns) {
    const columnCellIds: string[] = [];

    cells.push({
      id: resultId(c.col),
      type: "result",
      col: c.col,
      row: 0,
      expected: c.resultDigit,
      required: true,
      dependsOn: [...previousColumnCellIds],
    });
    columnCellIds.push(resultId(c.col));

    // A carry cell exists for every column except the last (its carry, if any,
    // becomes the overflow leading digit instead). A minnessiffra of 0 is never
    // written, so it is present but not required.
    if (c.col < columns.length - 1) {
      cells.push({
        id: carryId(c.col),
        type: "carry",
        col: c.col + 1,
        row: 0,
        expected: c.carryOut,
        required: c.carryOut > 0,
        dependsOn: [...previousColumnCellIds],
      });
      columnCellIds.push(carryId(c.col));
    }

    previousColumnCellIds = columnCellIds;
  }

  if (overflowDigit !== null) {
    cells.push({
      id: resultId(columns.length),
      type: "result",
      col: columns.length,
      row: 0,
      expected: overflowDigit,
      required: true,
      dependsOn: [...previousColumnCellIds],
    });
  }

  return { cells };
}

/**
 * Checks every cell against the true value, then (for cells whose expected
 * value depends on an earlier written digit) against the value that follows
 * from the child's own earlier entries. A cell wrong only because an earlier
 * carry was mis-copied is a följdfel, not a fresh error.
 */
export function checkAll(params: ColumnAddParams, written: WrittenMap): CheckReport {
  const { top, bottom } = params;
  const { columns, overflowDigit } = computeAdditionPlan(top, bottom);
  const results: CheckReport["results"] = [];
  let errorCount = 0;
  let followOnErrorCount = 0;

  const carryWritten = (col: number): number | undefined => {
    const v = written[carryId(col)];
    return typeof v === "number" ? v : undefined;
  };

  for (const c of columns) {
    // Result digit: true expected uses the true carry-in; the follow-on
    // expected substitutes the child's own written carry-in, if any.
    const carryIn = c.col === 0 ? 0 : carryWritten(c.col - 1);
    const trueSum = c.topDigit + c.bottomDigit + (c.col === 0 ? 0 : columns[c.col - 1].carryOut);
    const trueExpected = trueSum % 10;
    const followOnExpected =
      carryIn === undefined ? trueExpected : (c.topDigit + c.bottomDigit + carryIn) % 10;

    results.push(
      classify(resultId(c.col), written[resultId(c.col)], trueExpected, followOnExpected, true, (s) => {
        if (s === "wrong") errorCount++;
        if (s === "followOnError") followOnErrorCount++;
      })
    );

    if (c.col < columns.length - 1) {
      // Carry cells never depend on another written value — always structural.
      results.push(
        classify(
          carryId(c.col),
          written[carryId(c.col)],
          c.carryOut,
          c.carryOut,
          c.carryOut > 0,
          (s) => {
            if (s === "wrong") errorCount++;
          }
        )
      );
    }
  }

  if (overflowDigit !== null) {
    results.push(
      classify(resultId(columns.length), written[resultId(columns.length)], overflowDigit, overflowDigit, true, (s) => {
        if (s === "wrong") errorCount++;
      })
    );
  }

  return {
    results,
    errorCount,
    followOnErrorCount,
    allCorrect: results.every((r) => r.status === "correct" || r.status === "notRequired"),
  };
}

function classify(
  cellId: string,
  writtenValue: CellValue | undefined,
  trueExpected: CellValue,
  followOnExpected: CellValue,
  required: boolean,
  tally: (status: "correct" | "wrong" | "followOnError" | "unattempted" | "notRequired") => void
): CheckReport["results"][number] {
  if (!required) {
    tally("notRequired");
    return { cellId, status: "notRequired" };
  }
  if (writtenValue === undefined) {
    tally("unattempted");
    return { cellId, status: "unattempted" };
  }
  if (writtenValue === trueExpected) {
    tally("correct");
    return { cellId, status: "correct" };
  }
  if (writtenValue === followOnExpected) {
    tally("followOnError");
    return { cellId, status: "followOnError" };
  }
  tally("wrong");
  return { cellId, status: "wrong" };
}
